language: node_js
sudo: false
node_js:
- '0.10'
- '0.12'
- '4'
- '6'
install:
- npm install
- test -z "$BUILD_DOCS" || pip install --user sphinx
script:
- travis_retry npm run test-travis
- test -z "$BUILD_DOCS" || cd docs
- test -z "$BUILD_DOCS" || make html
- test -z "$BUILD_DOCS" || cd ..
after_success:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- test -z "$BUILD_DOCS" || CURRENT_HASH=`git rev-parse HEAD`
- test -z "$BUILD_DOCS" || RELEASE_VERSION=`git tag | xargs -I@ git log --format=format:"%ai @%n" -1 @ | sort | awk '{print $4}' | tail -n 1`
- test -z "$BUILD_DOCS" || RELEASE_HASH=`git rev-list $RELEASE_VERSION -n 1`
- test -z "$BUILD_DOCS" || if [ "$CURRENT_HASH" = "$RELEASE_HASH" ]; then DEPLOY_DOCS=true; fi
- test -z "$DEPLOY_DOCS" || git config --global user.email "evangelists@stormpath.com"
- test -z "$DEPLOY_DOCS" || git config --global user.name "express-stormpath Auto Doc Build"
- test -z "$DEPLOY_DOCS" || git clone git@github.com:stormpath/stormpath.github.io.git
- test -z "$DEPLOY_DOCS" || cd stormpath.github.io
- test -z "$DEPLOY_DOCS" || git fetch origin source:source
- test -z "$DEPLOY_DOCS" || git checkout source
- test -z "$DEPLOY_DOCS" || rm -rf source/nodejs/express/latest
- test -z "$DEPLOY_DOCS" || cp -r ../docs/_build/html source/nodejs/express/latest
- test -z "$DEPLOY_DOCS" || cp -r ../docs/_build/html source/nodejs/express/$RELEASE_VERSION
- test -z "$DEPLOY_DOCS" || git add --all
- test -z "$DEPLOY_DOCS" || git commit -m "express-stormpath release $RELEASE_VERSION"
- test -z "$DEPLOY_DOCS" || git push origin source
env:
  global:
  - secure: M4UcXsvhjYXupsD0D+bAWdopk9JjOxKnHi5OcqCSZ4lCn6XZ3KlxMQC/VM8Ryhe3Y5dAcNnJOJSE0eeK+ojZERY2UcozYSjEIdTZjGDI1L4HM538GeRz8wLEIG18gRdSjsyVGjAOed+eZ/MQwo2xyIjVPjJBFJuy2Djtt4fi1sw=
  - secure: LC2v9W0Nx8oviv+AajnXV1DOaiht+/1Hy92loa4a4Lbwz/NW0DmM9k1ollBFHpBhWVai3HaZKPl0XqdHqdq1fA2HppdJv8YbT/Hwkj1WdX+LRE/VUNevVc+MszlDJq1FOrgaEjiKyBqQP07RkZl4tg2kwpIET2Q0zmCubE7pezo=
  - secure: Uiqmlmp4O9noUngjFvl7hws+LpaHvy3lcwAAg4ecEotyE0T4b+kd1tvN5zSA2VEohPy/ynQK8zjevHqNoQzc4rUxTUsCijk1fnyOqrowvYrnSC0jwjkp4FaDaPk6HyEhGA6N37hl3km38iD09eqLwa4qA7SYgZEi5qRXLhnQxjo=
  - secure: h85DxO0pgB+tnszJIwfd/BDtmi1NKVfNuZertF3jitdPFFktlqF2ecDiAqgINpI4lNiJYac8eF8isTZn2Unh2K2SyElkZZfmhifz8n5MHqywidNYQKDz8BMBGELOxNQVkPgevPR5VU1eZoYUMDRgetC6hCp3iaRGoF6Xv+kAXl4=
  - secure: mBl0PWZag9Ji9jAYOEhCc9uORN9sGbbHD1IBkJD3kZ++tpMJO33ZUDHQix5BRSohhPgVqDm79XHpJiJ8PSIkQfvyMZNlWjGKqd/J9bdZbxSfO6+PdcSwS38Sr4hQsZyhYXhmragKzJI10vWBVJ/eDchYNLZfDaTjrPk7cSn9iPo=
  - secure: OlgbFdpSfZsyNN2utPJ3NUOUDjfx3gnrfmnYxJ/6LCB3Dp3Rfh+hrijWnHbg+GRhmaVjWYSd5iR419bn24hQToRmDaxwtfFreOdcx24D6Tak8tXWNo7I5B+lGpTG1lIdGWrOPW8w4MvcQY76HbbaHBZoA7dDiYtLI30uu8LgZ2Y=
  - secure: Z2+1Ln/B3LcuYgrF05qwF32BZzypRwCMgEXZPNtPbI7vL6qYbn5MCg2uv023OjvDd58LPwtwwaBxggLomoexiq1YHafadMXPiT6zGCeY72jHTQlVQN17WHYLfJ/1qzyKKsoFhN5Aqcved8cC1cOl8LoaqFUxswVLNdCXEGAbEhc=
matrix:
  include:
  - env: BUILD_DOCS=true
    node_js: 'node'
before_install:
- openssl aes-256-cbc -K $encrypted_3f9d201aa5b8_key -iv $encrypted_3f9d201aa5b8_iv
  -in deploy-key-stormpath-github-io-id-rsa.enc -out ~/.ssh/id_rsa
  -d
- chmod 600 ~/.ssh/id_rsa
deploy:
  provider: npm
  email: robert@robertjd.com
  api_key:
    secure: CGXnok9fZxVnAi3Gdx+Px4I9d5vCBsiPw3smMc2tcB4mFIcAVfEQeMjIq9eHO2ZBeZax1Sc6CVdRviN0t+sCvsiM29ncs4c2VlpePqRaa4Rc0JLOXz76pIYxGKh3sgd7VDBGIQJPaoIp0nZnG+6o9GAK03k2lMyEO8NgE/6ZcsM=
  on:
    tags: true
    repo: stormpath/express-stormpath
